return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.11.0",
  orientation = "orthogonal",
  width = 16,
  height = 40,
  tilewidth = 16,
  tileheight = 16,
  nextobjectid = 195,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../Set Piece Tiles/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../Set Piece Tiles/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tiles = 
      {
        {
          id = 6,
          properties = {
            ["id"] = "GRASS"
          },
          width = 64,
          height = 64
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 16,
      height = 40,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        46, 46, 46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 46, 46, 46, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        46, 46, 46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        46, 46, 46, 0, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        46, 46, 46, 0, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 46, 46, 46, 6, 46, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        46, 46, 46, 46, 46, 46, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0, 6, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 32,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 48,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 64,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 80,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 96,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 112,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 128,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 144,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 160,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 176,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 43,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 224,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 240,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 256,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 272,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 288,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 304,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 43,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 400,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 416,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 43,
          y = 560,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 203,
          y = 560,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 416,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 43,
          y = 16,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 59,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 75,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 91,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 107,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 155,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 171,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 187,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 203,
          y = 16,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 32,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 139,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 48,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 64,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 80,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 96,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 112,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 128,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 144,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 160,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 176,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 203,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 224,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 240,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 256,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 272,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 288,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 304,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 203,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 400,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 72.0062,
          y = 44.9938,
          width = 8,
          height = 8,
          rotation = 360.079,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 163,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 61,
          y = 101,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 166,
          y = 88,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 161,
          y = 164,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 103,
          y = 141,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 120,
          y = 101,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "blue_mushroom",
          shape = "rectangle",
          x = 60,
          y = 161,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 187,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 171,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 155,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 139,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 107,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 91,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 75,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 59,
          y = 192,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 187,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 171,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 155,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 123,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 91,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 75,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 59,
          y = 384,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 208,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 208,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 320,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 336,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 352,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 368,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 320,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 336,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 352,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 368,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 432,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 496,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 512,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 528,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 544,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 448,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 464,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 27,
          y = 480,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 432,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 448,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 464,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 480,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 496,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 512,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 528,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 219,
          y = 544,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 64.265,
          y = 232.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 134.265,
          y = 284.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 56.265,
          y = 295.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 175.265,
          y = 361.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 196.265,
          y = 295.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 62.265,
          y = 360.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 153.265,
          y = 244.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 129.265,
          y = 338.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "green_mushroom",
          shape = "rectangle",
          x = 197.265,
          y = 226.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 81.265,
          y = 548.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 60.265,
          y = 477.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 169.265,
          y = 485.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 168.265,
          y = 544.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 145.265,
          y = 436.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 111.265,
          y = 500.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 189.265,
          y = 419.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "red_mushroom",
          shape = "rectangle",
          x = 66.265,
          y = 420.86,
          width = 8,
          height = 8,
          rotation = 227.116,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 65.8431,
          y = 41.5847,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 191,
          y = 26,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 140,
          y = 68,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 74,
          y = 97,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 42,
          y = 64,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 74,
          y = 137,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 51,
          y = 180,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 111,
          y = 167,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 152,
          y = 132,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 158,
          y = 172,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 193,
          y = 151,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 193,
          y = 115,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 117,
          y = 26,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 131,
          y = 135,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 46,
          y = 218,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 49,
          y = 257,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 86,
          y = 241,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 97,
          y = 291,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 50,
          y = 335,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 60,
          y = 304,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 151,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 103,
          y = 353,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 80,
          y = 334,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 74,
          y = 358,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 152,
          y = 342,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 131,
          y = 369,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 143,
          y = 307,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 147,
          y = 273,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 187,
          y = 254,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 188,
          y = 317,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 173,
          y = 301,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 188,
          y = 355,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 162,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 162,
          y = 370,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 163,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 89,
          y = 263,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 164,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 97,
          y = 418,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 50,
          y = 396,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 60,
          y = 435,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 48,
          y = 462,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 52,
          y = 498,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 49,
          y = 538,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 87,
          y = 550,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 84,
          y = 503,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 92,
          y = 472,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 133,
          y = 487,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 107,
          y = 524,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 126,
          y = 523,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 160,
          y = 513,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 121,
          y = 556,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 180,
          y = 549,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 189,
          y = 501,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 162,
          y = 440,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 127,
          y = 455,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 160,
          y = 399,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 192,
          y = 451,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "poop",
          shape = "rectangle",
          x = 160,
          y = 491,
          width = 8,
          height = 8,
          rotation = -17.7353,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "scenario_trigger",
          type = "wall_stone",
          shape = "rectangle",
          x = 121,
          y = 273,
          width = 13,
          height = 15,
          rotation = 0,
          visible = true,
          properties = {
            ["scenario"] = "colourful_mushroom_farm"
          }
        },
        {
          id = 186,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 75.6667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 187.667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 59.6667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 171.667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 155.667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 139.667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 107.667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 91.6667,
          y = 560.667,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "",
          type = "wall_hay",
          shape = "rectangle",
          x = 124.667,
          y = 563,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
