return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.11.0",
  orientation = "orthogonal",
  width = 8,
  height = 8,
  tilewidth = 16,
  tileheight = 16,
  nextobjectid = 77,
  properties = {},
  tilesets = {
    {
      name = "ground",
      firstgid = 1,
      filename = "../../../../Set Piece Tiles/ground.tsx",
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "../../../../Set Piece Tiles/tiles.png",
      imagewidth = 512,
      imageheight = 384,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tiles = 
      {
        {
          id = 6,
          properties = {
            ["id"] = "GRASS"
          },
          width = 64,
          height = 64
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "BG_TILES",
      x = 0,
      y = 0,
      width = 8,
      height = 8,
      visible = true,
      opacity = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0,
        6, 0, 0, 0, 6, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      name = "FG_OBJECTS",
      visible = true,
      opacity = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 0,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 16,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 32,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 48,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "wall_wood",
          shape = "rectangle",
          x = 60,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {
            ["scenario"] = "healthy_resources"
          }
        },
        {
          id = 6,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 0,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 16,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 32,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 48,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 76,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 92,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 108,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 124,
          y = 60,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 76,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 92,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 108,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "wall_stone",
          shape = "rectangle",
          x = 60,
          y = 124,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 10.6667,
          y = 11,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 25.5,
          y = 11.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 39.1667,
          y = 12.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 40.5,
          y = 26.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 10.1667,
          y = 23.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 21.8333,
          y = 23.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 15.5,
          y = 46.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 8.5,
          y = 37.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 28.1667,
          y = 40.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 46.8333,
          y = 50.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 48.1667,
          y = 39.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 34.5,
          y = 45.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "grass",
          shape = "rectangle",
          x = 23.5,
          y = 32.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 87.6667,
          y = 18.6667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 110.833,
          y = 20.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 102.5,
          y = 11.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 98.1667,
          y = 23.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 81.1667,
          y = 27.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 76.8333,
          y = 40.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 90.1667,
          y = 42.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 92.8333,
          y = 27.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 106.167,
          y = 42.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 110.833,
          y = 31.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 103.167,
          y = 33.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 80.1667,
          y = 13.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "sapling",
          shape = "rectangle",
          x = 77.8333,
          y = 51.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 13.6667,
          y = 76.6667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 29.1667,
          y = 77.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 37.8333,
          y = 90.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 17.8333,
          y = 89.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 7.5,
          y = 99.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 8.83333,
          y = 113.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 26.1667,
          y = 103.167,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 26.8333,
          y = 115.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 41.8333,
          y = 106.167,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 46.1667,
          y = 115.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 45.8333,
          y = 78.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 53.1667,
          y = 91.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "berrybush",
          shape = "rectangle",
          x = 3.16667,
          y = 83.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 80,
          y = 78,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 95.5,
          y = 77.1667,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 113.833,
          y = 77.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 80.8333,
          y = 88.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 79.8333,
          y = 103.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 80.5,
          y = 115.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 94.8333,
          y = 91.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 91.1667,
          y = 103.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 94.8333,
          y = 115.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 108.167,
          y = 93.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 102.833,
          y = 102.833,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 111.833,
          y = 113.167,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "flower",
          shape = "rectangle",
          x = 120.833,
          y = 98.8333,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "firehound",
          shape = "rectangle",
          x = 30,
          y = 30,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "firehound",
          shape = "rectangle",
          x = 93.5,
          y = 34.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "firehound",
          shape = "rectangle",
          x = 95.5,
          y = 94.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "firehound",
          shape = "rectangle",
          x = 28.5,
          y = 93.5,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
